### ISSUE TITLE
lj2b IndexError: list index out of range (related to comments)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hitrust/google-blog-converters-appengine#21]
```
This happened when using the bin/livejournal2blogger.sh script after it 
has run for a while.

Traceback (most recent call last):
  File "bin/../src/livejournal2blogger/lj2b.py", line 480, in <module>
    translator.Translate(sys.stdout)
  File "bin/../src/livejournal2blogger/lj2b.py", line 202, in Translate
    comments = self._GetComments()
  File "bin/../src/livejournal2blogger/lj2b.py", line 325, in _GetComments
    comments.append(self._TranslateComment(comment, user_map))
  File "bin/../src/livejournal2blogger/lj2b.py", line 348, in 
_TranslateComment
    self._GetText(xml_comment.getElementsByTagName('body')[0]))
IndexError: list index out of range


```

Original issue reported on code.google.com by `zot...@gmail.com` on 17 Jan 2009 at 6:58

**Comment by GoogleCodeExporter** [comment]
```
Hi zotobi.

I'll take a look at this right away and will have a fix for it in an upcoming 
release.
```

Original comment by `jlu...@gmail.com` on 18 Jan 2009 at 9:35
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Any hope of this getting fixed? I just tried again and ran into the same error.
```

Original comment by `zot...@gmail.com` on 21 Oct 2009 at 9:10

**Comment by GoogleCodeExporter** [comment]
```
Hi, 

First of all, thnx for the tool.

Unfortunatelly, it's not working for me:

Error encountered during conversion.

Traceback (most recent call last):
File 
"/base/data/home/apps/wordpress2blogger/1.351455968489003159/wordpress2blogger.p
y", line 43, in post
translator.Translate(input, self.response.out)
File "/base/data/home/apps/wordpress2blogger/1.351455968489003159/wp2b.py", 
line 152, in Translate
error_string = self.GetSaxErrorString(doc, e.getLineNumber(), 
e.getColumnNumber(), ON_GAE)
File "/base/data/home/apps/wordpress2blogger/1.351455968489003159/wp2b.py", 
line 455, in GetSaxErrorString
bad_line = lines[line_num - 1]
IndexError: list index out of range

I got that error using your website (wordpress2blogger) and using the tool in 
my linux box too.

The error report is quite old. Is this supposed to be working? Maybe the export 
that I got from WP is not good....

Thnx
```

Original comment by `psgo...@gmail.com` on 3 Jul 2011 at 1:35
