### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hitrust/google-blog-converters-appengine#25]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?
Error encountered during conversion.

Traceback (most recent call last):
File "/base/data/home/apps/wordpress2blogger/1.330678570306190233/wordpress
2blogger.py", line 42, in post
translator.Translate(input, self.response.out)
File "/base/data/home/apps/wordpress2blogger/1.330678570306190233/wp2b.py",
 line 138, in Translate
xml.sax.parseString(doc, self)
File "/base/python_dist/lib/python2.5/xml/sax/__init__.py", line 49, in 
parseString
parser.parse(inpsrc)
File "/base/python_dist/lib/python2.5/xml/sax/expatreader.py", line 107, 
in parse
xmlreader.IncrementalParser.parse(self, source)
File "/base/python_dist/lib/python2.5/xml/sax/xmlreader.py", line 123, in 
parse
self.feed(buffer)
File "/base/python_dist/lib/python2.5/xml/sax/expatreader.py", line 211, 
in feed
self._err_handler.fatalError(exc)
File "/base/python_dist/lib/python2.5/xml/sax/handler.py", line 38, in 
fatalError
raise exception
SAXParseException: :2855:26: not well-formed (invalid token)


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `liujie....@gmail.com` on 2 Apr 2009 at 6:58

**Comment by GoogleCodeExporter** [comment]
```
Hi.

This is an error that indicates that the file that is being converted is not 
legal
XML.  I have seen some WordPress exports that are not legal XML.  If you'd like 
to
attach the WordPress file, perhaps we can just remove the offending characters 
and
try the conversion again.
```

Original comment by `jlu...@gmail.com` on 9 Apr 2009 at 5:24
- Changed state: **Accepted**
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
but i don't know which is the offeding characters....
```

Original comment by `liujie....@gmail.com` on 10 Apr 2009 at 1:34

**Comment by GoogleCodeExporter** [comment]
```
Here is my wordpress file that did not work with the same errors as above while 
using 
http://wordpress2blogger.appspot.com/
```

Original comment by `deepwap...@gmail.com` on 2 Sep 2009 at 2:42

Attachments:
- [wordpress.xml](https://storage.googleapis.com/google-code-attachments/google-blog-converters-appengine/issue-25/comment-3/wordpress.xml)

**Comment by GoogleCodeExporter** [comment]
```
I used an xml validator (http://www.validome.org/xml/validate/) and cleaned up 
some of 
the errors and the conversion worked.
```

Original comment by `deepwap...@gmail.com` on 2 Sep 2009 at 3:13
