### ISSUE TITLE
Wordpress2blogger error occured during conversion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hitrust/google-blog-converters-appengine#30]
```
What steps will reproduce the problem?
1. I exported my blog from wordpress and saved it on my computer
2. I try to convert my wordpress blog by using wordpress2blogger
3. An error occurs each time I try it 

What is the expected output? What do you see instead?

This comes up every time I try to convert my wordpress blog:

Error encountered during conversion.

Traceback (most recent call last):
File
"/base/data/home/apps/wordpress2blogger/1.333667862976265450/wordpress2blogger.p
y",
line 42, in post
translator.Translate(input, self.response.out)
File "/base/data/home/apps/wordpress2blogger/1.333667862976265450/wp2b.py",
line 140, in Translate
xml.sax.parseString(doc, self)
File "/base/python_dist/lib/python2.5/xml/sax/__init__.py", line 49, in
parseString
parser.parse(inpsrc)
File "/base/python_dist/lib/python2.5/xml/sax/expatreader.py", line 107, in
parse
xmlreader.IncrementalParser.parse(self, source)
File "/base/python_dist/lib/python2.5/xml/sax/xmlreader.py", line 123, in parse
self.feed(buffer)
File "/base/python_dist/lib/python2.5/xml/sax/expatreader.py", line 211, in
feed
self._err_handler.fatalError(exc)
File "/base/python_dist/lib/python2.5/xml/sax/handler.py", line 38, in
fatalError
raise exception
SAXParseException: :4043:381: not well-formed (invalid token)


What version of the product are you using? On what operating system?

I have windows vista

Please provide any additional information below.


```

Original issue reported on code.google.com by `cusumano...@gmail.com` on 23 May 2009 at 5:13

**Comment by GoogleCodeExporter** [comment]
```
Hi

I am not an expert but I hope I can help.
This error message SAXParseException: :4043:381: not well-formed (invalid token)
Means that the xml is "wrong" (non valid) at line 4043, the 381th character in 
this
line. (Use for exampel notepad++ to see this file). It is certainly an html tag
(<something> or </something>) which was missed..therefore the converter cannot 
make
sense of what it reads.

First back-up your xml, then try to delete the tag in this place...and repeat 
the
process until it passes ;-) As it happens on the 4000th lien only, I hope you 
may not
have too much of those and it may be achievable "by hand". Otherwise if you are
curious to learn (which I did for a similar reason)...look on the web for 
"regular
expressions" to clean up your xml (notepad++delas with that, editpad-pro is 
quite
good as well)
```

Original comment by `pierre.l...@gmail.com` on 25 May 2009 at 5:32

**Comment by GoogleCodeExporter** [comment]
```
Hi

Thanks so much for your help.

I tried to find the tag that was causing all the problems, but I couldn't, so I 
just
deleted my tags and tried to convert it to blogger.  But there's still an error
coming up: 

Error encountered during conversion.

Traceback (most recent call last):
File
"/base/data/home/apps/wordpress2blogger/1.333667862976265450/wordpress2blogger.p
y",
line 42, in post
translator.Translate(input, self.response.out)
File "/base/data/home/apps/wordpress2blogger/1.333667862976265450/wp2b.py", 
line 140,
in Translate
xml.sax.parseString(doc, self)
File "/base/python_dist/lib/python2.5/xml/sax/__init__.py", line 49, in 
parseString
parser.parse(inpsrc)
File "/base/python_dist/lib/python2.5/xml/sax/expatreader.py", line 107, in 
parse
xmlreader.IncrementalParser.parse(self, source)
File "/base/python_dist/lib/python2.5/xml/sax/xmlreader.py", line 123, in parse
self.feed(buffer)
File "/base/python_dist/lib/python2.5/xml/sax/expatreader.py", line 211, in feed
self._err_handler.fatalError(exc)
File "/base/python_dist/lib/python2.5/xml/sax/handler.py", line 38, in 
fatalError
raise exception
SAXParseException: :1:2: XML or text declaration not at start of entity

any suggestions??
```

Original comment by `cusumano...@gmail.com` on 26 May 2009 at 4:15

**Comment by GoogleCodeExporter** [comment]
```
In fact, Wordpress-to-Blogger is not a converting utility. I tried with my 
several
blogs, hosted in wordpress.com and wordpress.org as well, every time  problem 
exits.

I tried with both blogger & blogger draft too, but the former displays the info 
as
below whilst the later (draft.blogger.com) displays just ERROR IMPORTING ...
 Also tried with checked/unchecked publish post...
--------------
We're sorry, but we were unable to complete your request.

When reporting this error to Blogger Support or on the Blogger Help Group, 
please:

    * Describe what you were doing when you got this error.
    * Provide the following error code and additional information.

bX-jy70ay
Additional information
blogID: 3418807461169899657
host: www.blogger.com
uri: /import-blog.do

This information will help us to track down your specific problem and fix it! We
apologize for the inconvenience.
Find help

See if anyone else is having the same problem: Search the Blogger Help Group for
bX-jy70ay
If you don't get any results for that search, you can start a new topic. Please 
make
sure to mention bX-jy70ay in your message.

```

Original comment by `mermaida...@gmail.com` on 6 Jun 2009 at 6:24

**Comment by GoogleCodeExporter** [comment]
```
I'm getting the same error message today. Help!
```

Original comment by `Makphil...@gmail.com` on 10 Jun 2009 at 3:59
