### ISSUE TITLE
Movable Type to Blogger - Error encountered during conversion.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hitrust/google-blog-converters-appengine#40]
```
What steps will reproduce the problem?
1. File selected to import from Movable Type
2. "Convert" Button Selected
3. Error encountered.

What is the expected output? 
Correct file type

What do you see instead?
"Error encountered during conversion.

Traceback (most recent call last):
File
"/base/data/home/apps/movabletype2blogger/1.330678566209479651/movabletype2blogg
er.py",
line 44, in post
translator.Translate(StringIO.StringIO(input), self.response.out)
File
"/base/data/home/apps/movabletype2blogger/1.330678566209479651/mt2b.py",
line 211, in Translate
post_entry.title = atom.Title(text=self._Encode(value))
AttributeError: 'NoneType' object has no attribute 'title' "

What version of the product are you using? On what operating system?
http://movabletype2blogger.appspot.com/ 

Please provide any additional information below.


```

Original issue reported on code.google.com by `christop...@gmail.com` on 16 Oct 2009 at 2:03

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report.  This is a bug and I'll have a fix for it today.  I'll 
let you know 
when the hosted application is ready with the fix in place.
```

Original comment by `jlu...@gmail.com` on 16 Oct 2009 at 4:28
- Changed state: **Acc**

**Comment by GoogleCodeExporter** [comment]
```
Hi Christopher.

Would it be possible to attach a copy of your MovableType export file?   
```

Original comment by `jlu...@gmail.com` on 16 Oct 2009 at 4:46
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Hi JLUECK - Can I email it to ou directly? I'd rather not post it directly on 
public 
site.

Let me know.

Thanks,
Chris
```

Original comment by `christop...@gmail.com` on 16 Oct 2009 at 8:54

**Comment by GoogleCodeExporter** [comment]
```
Sure thing.  Just send it along to jlueck at gmail.  Thanks.
```

Original comment by `jlu...@gmail.com` on 16 Oct 2009 at 8:57

**Comment by GoogleCodeExporter** [comment]
```
Hi, I just met a similar issue:
$ bin/movabletype2blogger.sh ~/Plocha/export.mt
Traceback (most recent call last):
  File "bin/../src/movabletype2blogger/mt2b.py", line 319, in <module>
    translator.Translate(mt_file, sys.stdout)
  File "bin/../src/movabletype2blogger/mt2b.py", line 212, in Translate
    post_entry.title = atom.Title(text=self._Encode(value))
AttributeError: 'NoneType' object has no attribute 'title'


this is because in the export.mt file each entry starts with TITLE, while the 
script
expects the very first record to be AUTHOR. This seems wrong as
http://www.sixapart.com/movabletype/docs/mtimport states that "The order of the
metadata pieces is not important."
```

Original comment by `tropikha...@gmail.com` on 6 Apr 2010 at 9:21

**Comment by GoogleCodeExporter** [comment]
```
Ah.  Yes, thanks for the link.  I'll change up the structure of the 
movabletype2blogger translator to respect this 
rule.  
```

Original comment by `jlu...@gmail.com` on 6 Apr 2010 at 10:43

**Comment by GoogleCodeExporter** [comment]
```
I had a similar issue. I'm running the r89 converters. Is there a fix I can 
make to it?

Traceback (most recent call last):
  File "./bin/../src/movabletype2blogger/mt2b.py", line 327, in <module>
    translator.Translate(mt_file, sys.stdout)
  File "./bin/../src/movabletype2blogger/mt2b.py", line 217, in Translate
    post_entry.title = atom.Title(text=self._Encode(value))
AttributeError: 'NoneType' object has no attribute 'title'

Thanks - Lisa B.
```

Original comment by `Lease...@gmail.com` on 17 Oct 2011 at 3:00
