### ISSUE TITLE
Livejournal to blogger error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hitrust/google-blog-converters-appengine#69]
```
-What steps will reproduce the problem?
1. Use a blog converter.
2. Convert from livejournal to blogger export format.
3. Upload the blog to Blogger

-What is the expected output? What do you see instead?
When I try to export from https://livejournal2blogger.appspot.com/ it says

Error: Server Error

The server encountered an error and could not complete your request.
If the problem persists, please report your problem and mention this error 
message and the query that caused it.

-What version of the product are you using? On what operating system?
I'm first trying to export the blog.

Please provide any additional information below.

I also installed python to try to run the scripts or the project but it didn't 
make any difference. I tried to follow all the instructions but there is no 
example.

Can somebody help me? Thanks!


```

Original issue reported on code.google.com by `jordicat...@gmail.com` on 5 Apr 2011 at 9:35

**Comment by GoogleCodeExporter** [comment]
```
When running the python sample, try:

  google-blog-converters-r89/bin/livejournal2blogger.sh --help

If that works, it will give you the usage line for running the python 
application.

Let me know if you still encounter this error.
```

Original comment by `jlu...@google.com` on 6 Apr 2011 at 1:56
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
It says to execute lj2b.py -u username -p password [-s] but it doesn't make the 
difference. 

Do I have to modify the .py or the .sh to do the conversion?
```

Original comment by `jordicat...@gmail.com` on 6 Apr 2011 at 7:17

**Comment by GoogleCodeExporter** [comment]
```
Traceback (most recent call last):
  File "src/livejournal2blogger/lj2b.py", line 30, in <module>
    import gdata
ImportError: No module named gdata

What can I do?
```

Original comment by `jordicat...@gmail.com` on 6 Apr 2011 at 9:22

**Comment by GoogleCodeExporter** [comment]
```
Traceback (most recent call last):
  File "bin/../lib/googleappengine/python/dev_appserver.py", line 68, in <module>
    run_file(__file__, globals())
  File "bin/../lib/googleappengine/python/dev_appserver.py", line 64, in run_file
    execfile(script_path, globals_)
  File "/Users/jordicatala/Desktop/google-blog-converters-r89/lib/googleappengine/python/google/appengine/tools/dev_appserver_main.py", line 449, in <module>
    sys.exit(main(sys.argv))
  File "/Users/jordicatala/Desktop/google-blog-converters-r89/lib/googleappengine/python/google/appengine/tools/dev_appserver_main.py", line 392, in main
    config, matcher = dev_appserver.LoadAppConfig(root_path, {})
  File "/Users/jordicatala/Desktop/google-blog-converters-r89/lib/googleappengine/python/google/appengine/tools/dev_appserver.py", line 3464, in LoadAppConfig
    raise AppConfigNotFoundError
google.appengine.tools.dev_appserver.AppConfigNotFoundError

```

Original comment by `jordicat...@gmail.com` on 6 Apr 2011 at 9:43

**Comment by GoogleCodeExporter** [comment]
```
After putting in the user name and password at  
https://livejournal2blogger.appspot.com/ the webpage times out with an HTTP 500 
internal server error.
```

Original comment by `scottjb0...@gmail.com` on 27 Apr 2011 at 6:43
