### ISSUE TITLE
AttributeError: Binary instance has no attribute 'split'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hitrust/google-blog-converters-appengine#7]
```
What steps will reproduce the problem?
1. ./livejournal2blogger.sh -u float_dublin -p ***

What is the expected output? What do you see instead?
Traceback (most recent call last):
  File "./../src/livejournal2blogger/lj2b.py", line 465, in <module>
    translator.Translate(sys.stdout)
  File "./../src/livejournal2blogger/lj2b.py", line 198, in Translate
    posts = self._GetPosts()
  File "./../src/livejournal2blogger/lj2b.py", line 239, in _GetPosts
    posts.append(self._TranslatePost(event['events'][0]))
  File "./../src/livejournal2blogger/lj2b.py", line 273, in _TranslatePost
    tags = taglist.split(',')
AttributeError: Binary instance has no attribute 'split'

What version of the product are you using? On what operating system?
ubuntu hardy
Linux hvan 2.6.24-22-generic #1 SMP Mon Nov 24 18:32:42 UTC 2008 i686 GNU/Linux
Python 2.5.2

Tried trunk
Repository Root: http://google-blog-converters-appengine.googlecode.com
Revision: 49

Please provide any additional information below.
seems to be same problem as 'AttributeError: Binary instance has no
attribute 'replace''
http://code.google.com/p/google-blog-converters-appengine/issues/detail?id=4

```

Original issue reported on code.google.com by `Kostya.H...@gmail.com` on 13 Jan 2009 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
That is the same bug as issue #4.  I'll have this fixed in the next release 
(coming
soon!)
```

Original comment by `jlu...@gmail.com` on 13 Jan 2009 at 4:08
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I have checked out trunk some hours ago and the issue was not fixed yet, why is 
it
closed? :-)
Please, don't close issues with status=Fixed unless fix is commited.
```

Original comment by `mathemonkey` on 14 Jan 2009 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
That is my mistake.  If you are still experiencing a problem with the latest
repository, then this should be open.  I thought that it had been fixed with 
the fix
for issue #2
```

Original comment by `jlu...@gmail.com` on 14 Jan 2009 at 8:40
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
sorry, issue #4
```

Original comment by `jlu...@gmail.com` on 14 Jan 2009 at 8:41

**Comment by GoogleCodeExporter** [comment]
```
I've checked in a change which fixes this issue.  I've tested it on some 
non-ASCII
tags from within LiveJournal.  If any non-ASCII UTF-8 was in a tag, this error 
would
occur.

Please mark as verified if this fix works for you, mathemonkey
```

Original comment by `jlu...@gmail.com` on 14 Jan 2009 at 8:52
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
AttributeError have dissapeared but see issue 15
http://code.google.com/p/google-blog-converters-appengine/issues/detail?id=15
```

Original comment by `Kostya.H...@gmail.com` on 14 Jan 2009 at 9:11

**Comment by GoogleCodeExporter** [comment]
```
jlueck, yes, it works after r60. 
```

Original comment by `mathemonkey` on 14 Jan 2009 at 9:27
