### ISSUE TITLE
blogger2wordpress conversion issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hitrust/google-blog-converters-appengine#77]
```
What steps will reproduce the problem?

Run the conversion through terminal on Mac OS X 10.7.2


What is the expected output? What do you see instead?

Wordpress XML file

instead:

ryascolot$ google-blog-converters-r89/bin/blogger2wordpress.sh 
blog-10-18-2011.xml > wordpress-blog-10-18-2011.xml
Traceback (most recent call last):
  File "google-blog-converters-r89/bin/../src/blogger2wordpress/b2wp.py", line 28, in <module>
    import wordpress
  File "/Users/ryascolot/Downloads/google-blog-converters-r89/src/blogger2wordpress/wordpress.py", line 55, in <module>
    element_tree_write = ElementTree.ElementTree._write
AttributeError: type object 'ElementTree' has no attribute '_write'



What version of the product are you using? On what operating system?

Mac OS X 10.7.2

Please provide any additional information below.


```

Original issue reported on code.google.com by `rloth...@gmail.com` on 18 Oct 2011 at 7:58

**Comment by GoogleCodeExporter** [comment]
```
Same here, using windows 7
```

Original comment by `di...@sv2.com.br` on 26 Oct 2011 at 9:01

**Comment by GoogleCodeExporter** [comment]
```
C:\google-blog-converters-r89\bin>blogger2wordpress.bat blog-09-23-2011.xml > te
st.xml
Traceback (most recent call last):
  File "\google-blog-converters-r89\bin\..\src\blogger2wordpress\b2wp.py", line
28, in <module>
    import wordpress
  File "C:\google-blog-converters-r89\src\blogger2wordpress\wordpress.py", line
55, in <module>
    element_tree_write = ElementTree.ElementTree._write
AttributeError: type object 'ElementTree' has no attribute '_write'
```

Original comment by `di...@sv2.com.br` on 26 Oct 2011 at 9:06

**Comment by GoogleCodeExporter** [comment]
```
Some here using Linux, Max OS X 10.7.2 and Windows 7 64 Bit - I really want 
this to work :)
```

Original comment by `kenn...@fiil.eu` on 27 Oct 2011 at 7:09

**Comment by GoogleCodeExporter** [comment]
```
Same problem Win7 x64 and x86 Ubuntu
```

Original comment by `shke...@gmail.com` on 4 Dec 2011 at 9:32

**Comment by GoogleCodeExporter** [comment]
```
It appears this error is a Python versioning issue, at least for OS X Lion 
10.7.2. I modified blogger2wordpress.sh to use the Apple-provided python2.5 
binary instead of the Apple-default python (2.7) binary. All I had to do was 
change line 13 from:

PYTHONPATH=${PROJ_DIR}/lib python ${PROJ_DIR}/src/blogger2wordpress/b2wp.py $*

to:

PYTHONPATH=${PROJ_DIR}/lib python2.5 ${PROJ_DIR}/src/blogger2wordpress/b2wp.py 
$*

Now the blogger2wordpress script works for me as expected.
```

Original comment by `fantasti...@gmail.com` on 28 Dec 2011 at 4:21

**Comment by GoogleCodeExporter** [comment]
```
Comment #5 by fantasti...@gmail.com resolved this same issue for me today on 
Mac OSX 10.7.3. 
```

Original comment by `jmcn...@aerialservicesinc.com` on 14 May 2012 at 4:15

**Comment by GoogleCodeExporter** [comment]
```
This took care of the issue for as well. I'm using Mac OS 10.8.4. I tried 
several other versions but this (python2.5) is the only one that worked.
```

Original comment by `ryan.bur...@gmail.com` on 30 Aug 2013 at 11:51

**Comment by GoogleCodeExporter** [comment]
```
The fix provided by fantasti...@gmail.com worked for me as well! Great work!!!
```

Original comment by `MIXTRAPN...@gmail.com` on 24 Dec 2013 at 11:05

**Comment by GoogleCodeExporter** [comment]
```
In 10.10.3 of MacOS I changed the line in blogger2wordpress.sh to:

PYTHONPATH=${PROJ_DIR}/lib python2.6 ${PROJ_DIR}/src/blogger2wordpress/b2wp.py 
$*


```

Original comment by `artl...@gmail.com` on 30 Apr 2015 at 6:42
